- 2588

In [2]:
m, n = map(int, input().split())
# 3
print(f'3: {m * ((n // 1 ) % 10)}')     # (n // 10 ** 0) % 10
print(f'4: {m * ((n // 10) % 10)}')     # (n // 10 ** 1) % 10
print(f'5: {m * ((n // 100) % 10)}')    # (n // 10 ** 2) % 10
print(f'6: {m * n}')

3: 2360
4: 3776
5: 1416
6: 181720


In [36]:
a = int(input())
b = input()

print(a*int(b[2]))
print(a*int(b[1]))
print(a*int(b[0]))
print(a*int(b))

2360
3776
1416
181720


- 25304

In [3]:
X = int(input())    # 260000
N = int(input())    # 4
receipt = []
for i in range(N):
    a, b = map(int,input().split())
    receipt.append((a, b))

In [4]:
receipt

[(20000, 5), (30000, 2), (10000, 6), (5000, 8)]

In [5]:
costco_sum = 0
for a, b in receipt:
    costco_sum += a * b
print(costco_sum)

260000


In [37]:
x = int(input())            # 총금액    
n = int(input())            # 물건개수
sum = 0
for i in range(n):
  price, cnt = map(int, input().split())
  sum += (price*cnt)

if x == sum:
  print("Yes")
else:
  print("No")


Yes


- 2562

In [7]:
c = [3, 29, 38, 12, 57, 74, 40, 85, 61]
cmax, cindex = 0, 0
for index, element in enumerate(c):
    if cmax < element:
        cmax = element
        cindex = index
print(f'index={cindex}, {cindex+1}번째 값, {cmax}')

index=7, 8번째 값, 85


In [65]:
a = []
for i in range(9):
    x = int(input())
    a.append(x)
print(max(a))
print(a.index(max(a))+1)


85
8


- 2675

In [9]:
T = int(input())
test_case = []
for _ in range(T):
    cmd = input().split()
    R = int(cmd[0])
    test_case.append(cmd)
print(test_case)

[['3', 'ABC'], ['5', '/HTP']]


In [13]:
for R, S in test_case:
    result = ''
    r = int(R)
    for s in S:
        result += s * r
    print(result)

AAABBBCCC
/////HHHHHTTTTTPPPPP


- 10809

In [14]:
char_dict = {}
for i in range(26):
    c = chr(ord('a') + i)
    char_dict[c] = -1
print(char_dict)

{'a': -1, 'b': -1, 'c': -1, 'd': -1, 'e': -1, 'f': -1, 'g': -1, 'h': -1, 'i': -1, 'j': -1, 'k': -1, 'l': -1, 'm': -1, 'n': -1, 'o': -1, 'p': -1, 'q': -1, 'r': -1, 's': -1, 't': -1, 'u': -1, 'v': -1, 'w': -1, 'x': -1, 'y': -1, 'z': -1}


In [15]:
word = 'baekjoon'
for i in range(26):
    c = chr(ord('a') + i)
    print(word.find(c), end=' ')

1 0 -1 -1 2 -1 -1 -1 -1 4 3 -1 -1 7 5 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 

In [16]:
char_dict = {}
word = 'a quick brown fox'
for i in range(26):
    c = chr(ord('a') + i)
    char_dict[c] = word.find(c)     # find()는 찾는 문자열이 없으면 -1을 리턴함
print(char_dict)

{'a': 0, 'b': 8, 'c': 5, 'd': -1, 'e': -1, 'f': 14, 'g': -1, 'h': -1, 'i': 4, 'j': -1, 'k': 6, 'l': -1, 'm': -1, 'n': 12, 'o': 10, 'p': -1, 'q': 2, 'r': 9, 's': -1, 't': -1, 'u': 3, 'v': -1, 'w': 11, 'x': 16, 'y': -1, 'z': -1}


- 2908

In [17]:
for i in range(3):
    m, n = input().split()
    m_, n_ = int(m[::-1]), int(n[::-1])
    max_val = m_ if m_ >= n_ else n_
    print(f'{m}, {n}: {max_val}')   

734, 893: 437
221, 231: 132
839, 237: 938


In [ ]:
a, b = map(int,input().split())
ra = int(str(a)[::-1])
rb = int(str(b)[::-1])
if ra > rb:
    print(ra)
else:
    print(rb)

- 3003

In [18]:
# king, queen, rook, bishop, knight, pawn
chess_pieces = [1, 1, 2, 2, 2, 8]
pieces = list(map(int, input().split()))
for i in range(len(chess_pieces)):
    print(chess_pieces[i] - pieces[i], end=' ')

-1 1 -2 1 -1 3 

- 2444

In [21]:
N = 5
for i in range(N):
    line = ' ' * (N - i - 1) + '*' * (2 * i + 1)
    print(line)
for i in range(1, N):
    line = ' ' * i + '*' * (2 * (N - i) - 1)
    print(line)

    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *


- 1157

In [22]:
alpha_dict = {}
string = 'A quick brown fox jumps over the lazy dog'
for i in range(26):
    c = chr(ord('a') + i)
    alpha_dict[c] = string.lower().count(c)
print(alpha_dict)

{'a': 2, 'b': 1, 'c': 1, 'd': 1, 'e': 2, 'f': 1, 'g': 1, 'h': 1, 'i': 1, 'j': 1, 'k': 1, 'l': 1, 'm': 1, 'n': 1, 'o': 4, 'p': 1, 'q': 1, 'r': 2, 's': 1, 't': 1, 'u': 2, 'v': 1, 'w': 1, 'x': 1, 'y': 1, 'z': 1}


In [23]:
alpha_items = list(alpha_dict.items())
alpha_items.sort(key=lambda x: x[1], reverse=True)
alpha_items[:5]

[('o', 4), ('a', 2), ('e', 2), ('r', 2), ('u', 2)]

- 2738

In [27]:
A = [[1, 1, 1], [2, 2, 2], [0, 1, 0]]
B = [[3, 3, 3], [4, 4, 4], [5, 5, 100]]
C = []
for i in range(len(A)):
    temp = []
    for k in range(len(A[i])):
            temp.append(A[i][k] + B[i][k])
    C.append(temp)
    
for i in range(len(C)):
    for k in range(len(C[i])):
        print(C[i][k], end=' ')
    print()

4 4 4 
6 6 6 
5 6 100 


In [28]:
C = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
for i in range(len(A)):
    for k in range(len(A[i])):
        C[i][k] = A[i][k] + B[i][k]
    
for i in range(len(C)):
    for k in range(len(C[i])):
        print(C[i][k], end=' ')
    print()

4 4 4 
6 6 6 
5 6 100 


- Numpy를 사용해야 하는 이유

In [29]:
import numpy as np
A = np.array([[1, 1, 1], [2, 2, 2], [0, 1, 0]])
print(A)

[[1 1 1]
 [2 2 2]
 [0 1 0]]


In [30]:
B = np.array([[3, 3, 3], [4, 4, 4], [5, 5, 100]])
print(B)

[[  3   3   3]
 [  4   4   4]
 [  5   5 100]]


In [31]:
# 벡터화 연산
C = A + B
print(C)

[[  4   4   4]
 [  6   6   6]
 [  5   6 100]]
